project:
  name: 'CityWalker'
  run_name: 'test_dbr_online'
  result_dir: 'results'

training:
  batch_size: 4  # Smaller batch for online depth
  max_epochs: 2  # Short training for testing
  gpus: 1  # Single GPU
  amp: false  # Disable mixed precision for debugging
  normalize_step_length: true
  resume: false
  direction_loss_weight: 5.0
  feature_loss_weight: 0.1

scheduler:
  name: 'cosine'
  step_size: 10
  gamma: 0.1

optimizer:
  name: 'adamw'
  lr: 2e-4
  weight_decay: 0.0

model:
  type: 'citywalker_feat'
  do_rgb_normalize: true
  do_resize: true
  
  # Enable DBR (Depth Barrier Regularization)
  use_dbr: true
  
  # DBR configuration
  dbr:
    num_bins: 16
    temperature: 20.0
    crop_bottom_ratio: 0.6
    fov_horizontal: 90.0
    margin: 0.3
    weight: 2.0
    # Camera intrinsics (adjust based on your dataset)
    fx: 320.0
    fy: 320.0
    cx: 320.0
    cy: 180.0
  
  obs_encoder:
    type: 'dinov2_vitb14'
    context_size: 5
    crop: [350, 630]
    resize: [350, 630]
    freeze: true
  
  output_coordinate_repr: 'euclidean'

  cord_embedding:
    type: 'input_target'
    num_freqs: 6
    include_input: true

  encoder_feat_dim: 768

  decoder:
    type: 'attention'
    len_traj_pred: 5
    num_heads: 8
    num_layers: 16
    ff_dim_factor: 4

data:
  type: citywalk_feat
  # Root path to vast storage where datasets are stored
  vast_path: '/vast/hs5580/data/citywalker'
  # Relative paths from vast_path root (videos are directly in citywalk_2min/, poses in citywalk_2min/poses/)
  video_dir: 'citywalk_2min'
  pose_dir: 'citywalk_2min/poses'
  
  # Online depth inference (NO preprocessing needed!)
  depth_mode: 'online'  # 'online' or 'precomputed'
  depth_checkpoint: 'thirdparty/Depth-Anything-V2/metric_depth/checkpoints/depth_anything_v2_metric_vkitti_vits.pth'
  depth_model_size: 'small'  # 'small', 'base', or 'large'
  depth_max_depth: 20.0
  
  num_workers: 2  # Fewer workers for online depth (to avoid OOM)
  pose_fps: 5
  video_fps: 30
  target_fps: 1
  # Small dataset for testing
  num_train: 100
  num_val: 20
  num_test: 10
  input_noise: 0.1
  search_window: 50
  arrived_threshold: 5
  arrived_prob: 0.3

validation:
  num_visualize: 20

testing:
  num_visualize: 10

logging:
  enable_wandb: false
  pbar_rate: 10

